export const LABELS = {
  CONFIRM: "확인",
  SAVE: "저장",
  CANCEL: "취소",
  DELETE: "삭제",
  LOGIN: "로그인",
  LOGOUT: "로그아웃",
  ID: "아이디",
  PASSWORD: "비밀번호",
  HOME_TITLE: "vFRAS 가입자 관리",
  SEARCH: "검색",
  MY_INFO: "내 정보",
  USER_REGISTER: "사용자 등록",
  USER_EDIT: "사용자 정보 수정",
  SEARCH_RESULT : (result) =>  `검색결과 : ${result}건`,
  EDIT : "수정",
  PASSWORD_CHANGE : "비밀번호 변경",
  APPROVE : "승인",
  SUBSRIBER_TYPE  : "가입자 타입",
  SERVICE_TYPE : "서비스 타입",
  USER_STATE : "가입자 상태",
  SUBSRIBE : "가입",
  SUBSRIBE_EDIT: "가입자 정보 수정",
  MAIN_NUMBER : "대표번호",
  ALL_CHANGE : "전체 변경",
  COUNT_RESULT : (result) => `개수 ${result}개`,
  STATION_CHANGE_NUMBER : "변경할 국번 설정",
  STATION_CURRENT_NUMBER : "현재 설정된 국번",
  VIEW : "조회",
};
