export const LABELS = {
  CONFIRM: "확인",
  SAVE: "저장",
  CANCEL: "취소",
  DELETE: "삭제",
  LOGIN: "로그인",
  LOGOUT: "로그아웃",
  ID: "아이디",
  DEPARTMENT: "부서",
  NAME: "이름",
  PASSWORD: "비밀번호",
  PASSWORD_CONFIRM: "비밀번호 확인",
  PASSWORD_CHECK: "(8~20 영문/숫자/특수문자 혼합)",
  HOME_TITLE: "vFRAS 가입자 관리",
  SEARCH: "검색",
  MY_INFO: "내 정보",
  USER_REGISTER: "사용자 등록",
  USER_STATE: "사용자 상태",
  USER_EDIT: "사용자 정보 수정",
  CLASSIFICATION: "사용자 구분",
  SEARCH_RESULT: (result) => `검색결과 : ${result}건`,
  EDIT: "수정",
  PASSWORD_CHANGE: "비밀번호 변경",
  PASSWORD_RESET: "패스워드 초기화",
  APPROVE: "승인",
  SUBSCRIBER_TYPE: "가입자 유형",
  SERVICE_TYPE: "서비스 유형",
  SUBSCRIBER_STATE: "가입자 상태",
  SUBSCRIBE: "가입",
  SUBSCRIBER: "가입자",
  CREATED_AT: "가입일",
  SUBSCRIBER_NAME: "가입자명",
  SUBSCRIBER_VIEW: "가입자 조회",
  SUBSCRIBER_MANAGE: "가입자 관리",
  SUBSCRIBER_REGISTER: "가입자 등록",
  SUBSCRIBE_EDIT: "가입자 정보 수정",
  SUBSCRIBE_TYPE: "가입자 유형",
  ACCOUNT: "계정",
  ACCOUNT_MANAGE: "계정 관리",
  ACCOUNT_LOGS: "접속 이력",
  ACCESS_TIME: "접속 시간",
  LAST_ACCESS_TIME: "마지막 접속",
  COUNTRY_NUMBER: "국번호",
  COUNTRY_NUMBER_MANAGE: "LV 국번 관리",
  CONTENTS: "컨텐츠",
  SOUNDS_VIEW: "음원 조회",
  SOUNDS_CODE: "음원 코드",
  MAIN_NUMBER: "대표 번호",
  ALL_CHANGE: "전체 변경",
  TITLE_DESC: "제목/설명",
  COUNT_RESULT: (result) => `개수 ${result}개`,
  STATION_CHANGE_NUMBER: "변경할 국번 설정",
  STATION_CURRENT_NUMBER: "현재 설정된 국번",
  VIEW: "조회",
  LV_NUMBER: "(LV번호)",
  SETTING: "설정",
  STATE: "상태",
  APPLY_DATE: "신청일",
  USER_NUMBER_MULTI: "사용자 번호\\n(시작~끝)",
  PBX_NUMBER_COL_MULTI: "교환기 번호\\n(시작~끝)",
  EMAIL: "이메일",
  PHONE: "휴대폰",
  REMARKS: "비고",
  DID: "DID회선 및 부가서비스 설정",
  ADDRESS1: "주소1",
  ADDRESS2_OPTION: "주소2 (Option)",
  SUBSCRIBER_NUMBER: "가입자 번호(대표번호)",
  USER_NUMBER: "사용자 번호 (시작~끝)",
  PBX_NUMBER_COL: "교환기 번호 (시작~끝)",
  DEFAULT_CALLRING : "기본통화연결음 ID",
};
