export const LABELS = {
  CONFIRM: "확인",
  SAVE: "저장",
  CANCEL: "취소",
  DELETE: "삭제",
  LOGIN: "로그인",
  LOGOUT: "로그아웃",
  ID: "아이디",
  DEPARTMENT: "부서",
  NAME: "이름",
  PASSWORD: "비밀번호",
  CURRENT_PASSWORD: "현재 비밀번호",
  CHANGE_PASSWORD: "변경 비밀번호",
  PASSWORD_PLACEHOLDER: "******",
  CHANGE_PASSWORD_CONFIRM: "변경 비밀번호 재확인",
  PASSWORD_CONFIRM: "비밀번호 확인",
  PASSWORD_CHECK: "(8~20 영문/숫자/특수문자 혼합)",
  PASSWORD_CHECK2: "* 8~20자의 영문 대,소문자,숫자,특수문자",
  HOME_TITLE: "vFRAS 가입자 관리",
  SEARCH: "검색",
  ALERT_MSG: "알림",
  MY_INFO: "내 정보",
  USER_REGISTER: "사용자 등록",
  USER_STATE: "사용자 상태",
  USER_EDIT: "사용자 정보 수정",
  CLASSIFICATION: "사용자 구분",
  SEARCH_RESULT: (result) => `검색결과 : ${result}건`,
  EDIT: "수정",
  PASSWORD_CHANGE: "비밀번호 변경",
  PASSWORD_RESET: "비밀번호 초기화",
  APPROVE: "승인",
  SUBSCRIBER_TYPE: "가입자 유형",
  SERVICE_TYPE: "서비스 유형",
  SUBSCRIBER_STATE: "가입자 상태",
  SUBSCRIBE: "가입",
  SUBSCRIBER: "가입자",
  CREATED_AT: "가입일",
  SUBSCRIBER_NAME: "가입자명",
  SUBSCRIBER_VIEW: "가입자 조회",
  SUBSCRIBER_MANAGE: "가입자 관리",
  SUBSCRIBER_REGISTER: "가입자 등록",
  SUBSCRIBE_EDIT: "가입자 정보 수정",
  SUBSCRIBE_TYPE: "가입자 유형",
  ACCOUNT: "계정",
  ACCOUNT_MANAGE: "계정 관리",
  HISTORY: "접속 이력",
  ACCOUNT_DETAIL_LOGS: "접속 상세 이력",
  FINAL_ACCESS_TIME: "최종 접속 시간 : ",
  ACCESS_TIME: "접속 시간",
  LAST_ACCESS_TIME: "마지막 접속",
  COUNTRY_NUMBER: "국번호",
  COUNTRY_NUMBER_MANAGE: "LV 국번 관리",
  CONTENTS: "컨텐츠",
  SOUNDS_VIEW: "음원 조회",
  SOUNDS_CODE: "음원 코드",
  MAIN_NUMBER: "대표번호",
  ALL_CHANGE: "전체 변경",
  TITLE_DESC: "제목/설명",
  COUNT_RESULT: (result) => `개수 ${result}개`,
  STATION_CHANGE_NUMBER: "변경할 국번 설정",
  STATION_CURRENT_NUMBER: "현재 설정된 국번",
  VIEW: "조회",
  LV_NUMBER: "(LV번호)",
  SETTING: "설정",
  MANAGE: "관리",
  STATE: "상태",
  APPLY_DATE: "신청일",
  USER_NUMBER_MULTI: "사용자 번호\n(시작~끝)",
  PBX_NUMBER_COL_MULTI: "교환기 번호\n(시작~끝)",
  EMAIL: "이메일",
  PHONE: "휴대폰",
  REMARKS: "비고",
  DID_TITLE: "DID회선 및 부가서비스 설정",
  ADDRESS1: "주소1",
  ADDRESS2_OPTION: "주소2 (Option)",
  SUBSCRIBER_NUMBER: "가입자 번호(대표번호)",
  USER_NUMBER: "사용자 번호 (시작~끝)",
  PBX_NUMBER_COL: "교환기 번호 (시작~끝)",
  DEFAULT_CALLRING: "기본통화연결음 ID",
  CONTENT: "내용",
  INDEX: "순번",
  DID: "DID 회선",
  ADDITIONAL_SERVICE_SETTING: "부가서비스 설정",
  ADD_ITEM: "항목 추가",
  DEFAULT_RING: "기본링",
  SOUND_CODE_COL_MULTI: "음원 코드\n(기본링)",
  IS_ADDITIONAL_SERVICE: "부가서비스 가입여부 (왼쪽이 우선순위가 낮음)",
  CIRCULATION_RING: "순환링",
  DAY_OF_WEEKEND: "요일",
  CALLER_AREA: "발신지역",
  CALLER_NUMBER: "발신자번호",
  TIME_SLOT : "시간대",
  ANNIVERSARY: "기념일",
  IS_OPEN: "가입여부",
  CIRCULAR: "순환형",
  BY_TIME_ZONE: "시간대별",
  BY_DAY: "요일별",
  BY_SENDING_AREA: "발신지역별",
  BY_CALLER_NUMBER: "발신자번호별",
  BY_ANNIVERSARY: "기념일별",
  ADD: "추가",
  ALL_DELETE: "전체 삭제",
  BULK_APPLY: "일괄 적용",
  BULK_DELETE: "일괄 삭제",
  GREETING: "님 안녕하세요",
  ACCESS_IP: "접속 IP",
  DIVISION: "구분",
  ALL: "전체",
  PBX_NUMBER: "교환기 번호",
  USER_NUMBER_F: "사용자 번호",
  SAVE_ID: "아이디 저장",
  ADMIN_LOGIN: "관리자 로그인",
  PASSWORD_CHECK3: "(초기 비밀번호는 대표번호 마지막 4자리)",
  DIVISION_SEARCH: "검색 구분",
  CURRENT: "현재 ",
  DID_VALUE: `개 DID `,
  DID_TITLE_PERSONAL: "DID 회선 설정 - 개인",
  CORPORATION: "법인",
  GERNERAL_PERMISSIONS: "일반 권한",
  DEPARTMENT_PERMISSIONS: "부서 권한",
  MODIFY: "수정",
  DID_CONFIG_LENGH: (cnt, max) => `${cnt}개 (최대 ${max})`,
  INTERRUPT: "일시정지",
  START_DATE: "시작일",
  END_DATE: "종료일",
  RBT_ID: "음원코드",
  DAY_TYPE: "요일",
  START_TIME: "시작시간",
  END_TIME: "종료시간",
  ORGN: "지역",
  GROUP: "그룹",
  CALLING_NUMBER: "발신번호",
  DID_CALLING_PLACEHOLDER: "발신번호(','구분, 최대 5개)",
  TIME : "시간",
  RESET : "초기화"
};
